In [1]:
import pandas as pd

In [42]:
with open('2018_senate_election_results.txt', 'r') as data:
        lines = data.readlines()

In [43]:
type(lines)

list

In [44]:
precinct=[]
rep=[]
dem=[]
lib=[]
over_votes=[]
under_votes=[]

In [45]:
for line in lines:
    precinct.append(line[0:4])
    rep.append(line[37:41])
    dem.append(line[44:47])
    lib.append(line[51:53])
    over_votes.append(line[58:59])
    under_votes.append(line[63:65])

In [56]:
senate_df=pd.DataFrame({'precinct':precinct,'rep':rep,'dem':dem,'lib':lib,'over_votes':over_votes,'under_votes':under_votes})

In [57]:
senate_df.head()

  precinct   rep  dem lib over_votes under_votes
0     1001    65  344   3          0           2
1     1002   113  243   3          0           2
2     1003   125  867  12          0           5
3     1004    50  294   2          0           5
4     1005    55  240   3          0           1

In [58]:
senate_df.apply(lambda x: x.str.strip())

    precinct  rep  dem lib over_votes under_votes
0       1001   65  344   3          0           2
1       1002  113  243   3          0           2
2       1003  125  867  12          0           5
3       1004   50  294   2          0           5
4       1005   55  240   3          0           1
5       1006  154  718   0          0           4
6       1007  127  474   2          0           3
7       1008  136  887   5          0           3
8       1009  281  495   9          0           4
9       1010   51  262   0          0           2
10      1011   48  141   0          0           1
11      1012  251  591   7          0           5
12      1013  139  807   7          0           8
13      1014   69  390   4          0           0
14      1015   89  381   3          0           4
15      1016   69  364   2          0           2
16      1017   30   54   0          0           1
17      1018  166  674   8          0           1
18      1019   61  245   5          0           1
19      1020  219  748  10          0           6
20      1021  133  523   7          0           3
21      1022   78  296   1          0           4
22      1023  120  736   7          0          10
23      1024  482  965  15          0           7
24      1025   24  154   1          0           0
25      1026   76  382   3          0           2
26      1027   45   72   1          0           0
27      1028   90  290   5          0           8
28      1029  138  611   6          0           8
29      1030    8    9   0          0           0
..       ...  ...  ...  ..        ...         ...
721     4208    0    0   0          0           0
722     4209   23    4   0          0           0
723     4210    2    4   0          0           0
724     4211    0   20   0          0           0
725     4212    0    0   0          0           0
726     5020   22   91   1          0           0
727     5021   10   83   0          0           0
728     5023   18   53   1          0           0
729     5028    5   11   0          0           0
730     5035    6   37   0          0           0
731     6020  237  405   2          0           0
732     6021   22   34   0          0           0
733     6023    6   14   0          0           0
734     6028   17   20   2          0           0
735     6035    2   13   0          0           0
736     6120    2    2   0          0           0
737     6121   11    9   0          0           0
738     6123    0    1   0          0           0
739     6128    2    2   0          0           0
740     6135    4    7   0          0           0
741     6220   13   17   0          0           0
742     6221    1    1   0          0           0
743     6223    2    3   0          0           0
744     6228    2    9   0          0           0
745     6235    0    0   0          0           0
746     6320    1    2   0          0           0
747     6321    3    3   0          0           0
748     6323    0    0   0          0           0
749     6328    0    0   0          0           0
750     6335   10    8   0          0           0

[751 rows x 6 columns]

In [59]:
senate_df['rep']=pd.to_numeric(senate_df['rep'])
senate_df['dem']=pd.to_numeric(senate_df['dem'])
senate_df['lib']=pd.to_numeric(senate_df['lib'])
senate_df['over_votes']=pd.to_numeric(senate_df['over_votes'])
senate_df['under_votes']=pd.to_numeric(senate_df['under_votes'])

In [60]:
senate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 6 columns):
precinct       751 non-null object
rep            751 non-null int64
dem            751 non-null int64
lib            751 non-null int64
over_votes     751 non-null int64
under_votes    751 non-null int64
dtypes: int64(5), object(1)
memory usage: 35.3+ KB

In [ ]:
senate_df['total'] = senate_df['rep']+senate_df['dem']+senate_df['lib']